### ISSUE TITLE
Mautic 4 Compatibility

### ISSUE THREAD

**Issue by kaseyhackspace** [mzagmajster/mautic-mailgun-mailer-plugin#3]
Hi, just wanted to ask if this fork is compatible with Mautic v4? Thanks!

**Comment by mzagmajster** [comment]
No, not yet, but I plan to migrate it to M4

**Comment by kaseyhackspace** [comment]
Thanks @mzagmajster , I did a simple test and email was received. Yet to test extensively though :)

**Comment by mzagmajster** [comment]
Plugin works on Mautic 4, without need for modifications.
